### ISSUE TITLE
"A stream must either be a resource or a string" exception

### ISSUE THREAD

**Issue by rseliberty** [akeneo/BatchBundle#87]
Hi,
I use 0.4.4 version of akeneo batch bundle
which used monolog/monolog: ^1.1.0 so 1.17.1 actually.

When I wan't to call "akeneo:batch:job" command, I have an exception : "A stream must either be a resource or a string"

After search, Akeneo\Bundle\BatchBundle\Monolog\Handler\ BatchLogHandler call the parent with "false" value parameter (line 30), but the parent "Monolog\Handler\StreamHandler" don't accept boolean value in his constructor.
So there is this exception "throw new \InvalidArgumentException('A stream must either be a resource or a string.');"

I correct this in BatchLogHandler :
public function __construct($logDir)
    {
        $this->logDir = $logDir;
        parent::__construct($this->logDir);
    }

There is the good way ? Or I have made an error ?

Thanks
Romain

**Comment by ste93cry** [comment]
:+1: bug confirmed, it prevents this bundle from being used. First thing at all is a suggestion: please allow users to choose if they want logging enabled via config. To fix the bug, there are two options: you change the composer constraint to allow only Monolog versions up to the latest version compatible with your bundle, or you update your bundle to be compatible with newer versions of Monolog (better solution). I unfortunately see a really small activity on this bundle (which is great). Do you plan to fix all these bugs soon? I could provide a PR if you assure us that you will merge it and release a new version of the bundle as soon as possible

**Comment by nidup** [comment]
Hi @ste93cry, 

We've extracted this bundle in our main dev repository https://github.com/akeneo/pim-community-dev/tree/master/src/Akeneo to re-work it (split into a library + a bundle) and the v0.5/master now resides into this repository.

We would follow the same strategy than Symfony or Sylius, means working in our main repo and use subtree split script to synchronize this lib + bundles in dedicated read only repositories to make this library usable outside of our Akeneo PIM project.

You can find here information about what we've reworked https://github.com/akeneo/pim-community-dev/blob/master/UPGRADE-1.5.md#batch-bundle--component 

Our bad, we didn't take time for now to communicate about this change, neither to write scripts to synchronize.

This bug is still present in the https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Bundle/BatchBundle/Monolog/Handler/BatchLogHandler.php

I would love work together on this fix, i do agree, we should bump the monolog version but as our destination file for the log is dynamic (one per job execution) it looks not that easy with the last version of monolog (I didn't dive too much inside).

**Comment by ste93cry** [comment]
>We would follow the same strategy than Symfony or Sylius, means working in our main repo and use subtree split script to synchronize this lib + bundles in dedicated read only repositories to make this library usable outside of our Akeneo PIM project.

This is great!

>Our bad, we didn't take time for now to communicate about this change, neither to write scripts to synchronize.

Before ever working on any fix, it would be great if you can create and syncronize the standalone repositories.

**Comment by ste93cry** [comment]
@nidup Any news on the sync of this standalone repository with the main one?

**Comment by nidup** [comment]
@ste93cry not advanced a single step with this for now, lot of new questions, what branching strategy, what about BC break, etc. We release new minor versions of akeneo/pim-community-dev every 6 months and could imho follow the main repo branching (symfony style), not ideal from this bundle point of view but far more easier to handle.

**Comment by nidup** [comment]
Today, I moved on the extraction topic, you could be interested by the linked PR :dancer:

**Comment by nidup** [comment]
The issue has been fixed in our main repository  https://github.com/akeneo/pim-community-dev/commit/7585d96185274f86236c09027357c7ed6e13a37e

:tada: I finally managed to write our synchronization scripts :tada:

So, the master of this repository is now updated through a subtree split from our main repository and the fix has bee applied here too. Sadly, there is still an issue to use the BatchBundle outside of Akeneo PIM (related to StorageUtilsBundle dependency, I'm working on it).

We've extracted a php library from this bundle https://github.com/akeneo/batch which is usable in a standalone mode.

We're working a lot on the library and the bundle for our upcoming PIM 1.6 release, more to come, stay tuned :wink:
